@startuml Kaspersky Fraud Prevention
skinparam ParticipantPadding 20
skinparam BoxPadding 10

box #F0F0F0
actor Mobile
participant KFP_SDK
end box

box "Magnit" #LightGreen
participant Gateway
participant AuthV2
participant other_services
end box

box "Kaspersky" #FFBBBB
participant Kaspersky
end box


== Инициализация приложения ==

Mobile -> Gateway ++ : Запрос фичатоглов для неавторизованной зоны
return Mobile_toggles_unauthorized
note right
  X-Device-Tag: ''
end note

alt is_kfp_enabled is true
  Mobile -> KFP_SDK ++ : login
  KFP_SDK -> KFP_SDK: формирует и возвращает\n<b>device_tag</b>
  return device_tag
  KFP_SDK -> Kaspersky: Device fingerprint + device_tag
else #ffeeee
  Mobile -> Mobile:
  note right
    device_tag = ''
  end note
end

== POST v3/auth/otp ==
Mobile -> Gateway: /v3/auth/otp (phone_number)
Gateway -> AuthV2: /v1/auth/otp
note right
  X-Device-Tag: device_tag

  Информация о запросе не будет отправлена в KFP (но записана в лог)\nесли X-Device-Tag:
  - пустой
  - имеет значение disabled
  - имеет значение legacy
end note
alt #e4fbe4 Security проверки пройдены
  AuthV2 -> Kaspersky: POST /login?cid=...&phase=login&action=score&uid=...&device=...&result=success&username=...
  Kaspersky -> AuthV2: response /login (200: результат проверки)

  alt #e4fbe4 Ответ от KFP нас устраивает
    AuthV2 -> other_services: Логика по отправке пользователю СМС
    AuthV2 -> Gateway: response /v1/auth/otp (200)
    Gateway --> Mobile: response /v3/auth/otp (200)
  else #ffeeee Ответ от KFP нас НЕ устраивает
    AuthV2 -> Gateway: response /v1/auth/otp (403)
    Gateway --> Mobile: response /v3/auth/otp (403)
  end
else #ffeeee Security проверки НЕ пройдены
  AuthV2 -> Kaspersky: POST /login?cid=...&phase=login&action=score&uid=...&device=...&result=fail
  Kaspersky -> AuthV2: response /login (202: результат)
  Gateway --> Mobile: response v3/auth/otp (422: с каким-то кодом ошибки внутри)
end


== POST v3/auth/token ==
Mobile -> Gateway: /v3/auth/token (phone_number, otp)
Gateway -> AuthV2: /v1/auth/token
AuthV2 -> AuthV2: логика по проверке OTP-кода
note right
  X-Device-Tag: device_tag

  Информация о запросе не будет отправлена в KFP (но записана в лог) если X-Device-Tag:
  - пустой
  - имеет значение disabled
  - имеет значение legacy
end note
alt #e4fbe4 OTP-код корректный
    AuthV2 -> Kaspersky: POST /login?cid=...&phase=challenge&challenge-type=sms&uid=...&device=...&result=success&username=...
else #ffeeee OTP-код некорректный
    AuthV2 -> Kaspersky: POST /login?action=score&cid=...&phase=login&uid=...&device=...&result=fail&username=...
end
    Kaspersky --> AuthV2: response /login (202: HTTP Accepted)
    AuthV2 -> Gateway: response /v1/auth/token (200 or 400: Invalid OTP Code)
    Gateway --> Mobile: response /v3/auth/token (200 or 400: Invalid OTP Code)

== POST любой запрос который мы хотим проверять через KFP ==
Mobile -> Gateway: ...
note right
  X-Device-Tag: device_tag

  Информация о запросе не будет отправлена в KFP если X-Device-Tag:
  - пустой
  - имеет значение disabled
  - имеет значение legacy
end note

alt #e4fbe4 метод входит в список "важных запросов"
  Gateway -> AuthV2: /v1/device/is-trusted
  AuthV2 -> Kaspersky: POST /events?cid=...&device=...&phase=post_login&operation=checkout&action=risk_level
  Kaspersky -> AuthV2: response /events (200: результат проверки)

  alt #e4fbe4 Ответ от KFP нас устраивает
    AuthV2 -> Gateway: response /v1/device/is-trusted (200, {isTrusted: true})
    Gateway -> Gateway: логика "важного запроса"
    Gateway --> Mobile: response (соответствующей успешному сценарию)
  else #ffeeee Ответ от KFP нас НЕ устраивает
    AuthV2 -> Gateway: response /v1/device/is-trusted (200, {isTrusted: false})
    Gateway --> Mobile: response (403)
  end
else метод не входит в список "важных запросов"
  Gateway -> Gateway: Старая логика без KFP
  return Соответствующий старой логике ответ
end

@enduml
